import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useUsers } from "@/hooks/user/useUsers";
import { Card, CardHeader, CardTitle, CardDescription, CardContent, } from "@/components/ui/card";
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell, } from "@/components/ui/table";
import { LuEye } from "react-icons/lu";
import { Button } from "@/components/ui/button";
import { Link } from "react-router-dom";
import { Badge } from "@/components/ui/badge";
export default function AdminUsers() {
    const { data: users = [], isLoading, isError } = useUsers();
    return (_jsxs("div", { className: "container mx-auto px-4 py-8 space-y-8", children: [_jsx("div", { className: "flex flex-col md:flex-row justify-between items-start md:items-center gap-4", children: _jsxs("div", { children: [_jsx("h1", { className: "text-3xl font-bold text-gray-800", children: "Usuarios" }), _jsx("p", { className: "text-gray-500 text-sm", children: "Administraci\u00F3n general de usuarios registrados" })] }) }), _jsxs(Card, { children: [_jsxs(CardHeader, { children: [_jsx(CardTitle, { className: "text-gray-800", children: "Listado" }), _jsxs(CardDescription, { className: "text-gray-500 text-sm", children: [users.length, " usuario(s) registrado(s)"] })] }), _jsx(CardContent, { children: isLoading ? (_jsx("p", { className: "text-center text-gray-500 py-8", children: "Cargando..." })) : isError ? (_jsx("p", { className: "text-center text-red-600 py-8", children: "Error al cargar usuarios" })) : (_jsxs("div", { className: "rounded-md border border-gray-200", children: [_jsxs(Table, { children: [_jsx(TableHeader, { children: _jsxs(TableRow, { children: [_jsx(TableHead, { children: "ID" }), _jsx(TableHead, { children: "Nombre" }), _jsx(TableHead, { children: "Email" }), _jsx(TableHead, { children: "Rol" }), _jsx(TableHead, { children: "Verificado" }), _jsx(TableHead, { children: "Estado" }), _jsx(TableHead, { className: "text-right", children: "Acciones" })] }) }), _jsx(TableBody, { children: users.map((user) => (_jsxs(TableRow, { children: [_jsxs(TableCell, { className: "font-medium text-gray-800", children: ["#", user.id] }), _jsxs(TableCell, { className: "text-gray-800", children: [user.first_name, " ", user.last_name ?? "", _jsx("div", { className: "text-xs text-gray-500", children: user.phone ?? "Sin teléfono" })] }), _jsx(TableCell, { className: "text-gray-800", children: user.email }), _jsx(TableCell, { children: _jsx(Badge, { className: "bg-blue-100 text-blue-700", children: user.role }) }), _jsx(TableCell, { children: user.is_verified ? (_jsx(Badge, { className: "bg-green-100 text-green-700", children: "S\u00ED" })) : (_jsx(Badge, { className: "bg-gray-100 text-gray-600", children: "No" })) }), _jsx(TableCell, { children: user.status ? (_jsx(Badge, { className: "bg-green-100 text-green-700", children: "Activo" })) : (_jsx(Badge, { className: "bg-red-100 text-red-700", children: "Inactivo" })) }), _jsx(TableCell, { className: "text-right", children: _jsx(Button, { asChild: true, variant: "ghost", size: "icon", children: _jsx(Link, { to: `/admin/users/${user.id}`, children: _jsx(LuEye, { className: "w-4 h-4" }) }) }) })] }, user.id))) })] }), users.length === 0 && (_jsx("div", { className: "text-center py-8 text-gray-500", children: "No hay usuarios registrados." }))] })) })] })] }));
}
