import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { LuSparkles, LuCrown } from "react-icons/lu";
import { Button } from "@/components/ui/button";
import { Link } from "react-router-dom";
export function AboutSection() {
    return (_jsx("section", { className: "w-full py-16 md:py-24 bg-[#D4AF37]/20 text-[#2C1810] relative overflow-hidden", children: _jsx("div", { className: "container mx-auto px-4 md:px-6", children: _jsxs("div", { className: "grid gap-12 lg:grid-cols-2 lg:gap-16 items-center", children: [_jsx("div", { className: "mx-auto w-full max-w-[500px] order-2 lg:order-1", children: _jsxs("div", { className: "relative", children: [_jsx("img", { src: "https://assets.isu.pub/document-structure/240405232936-b738ae961513affed82474a9bb1b96bc/v1/994c530e45dbe51793b3d29a8944121e.jpeg", width: 500, height: 600, alt: "Imagen de la historia de NURAE", className: "mx-auto object-cover rounded-2xl shadow-xl" }), _jsx("div", { className: "absolute -top-4 -right-4 bg-[#D4AF37] text-white p-4 rounded-full shadow-lg", children: _jsx(LuCrown, { className: "h-8 w-8" }) })] }) }), _jsxs("div", { className: "space-y-6 order-1 lg:order-2", children: [_jsxs("div", { className: "inline-flex items-center gap-2 rounded-full bg-[#D4AF37]/20 px-4 py-2 text-sm font-medium text-[#2C1810]", children: [_jsx(LuSparkles, { className: "h-4 w-4" }), "Nuestra Historia"] }), _jsx("h2", { className: "text-4xl md:text-5xl font-serif font-bold", children: "El lujo tambi\u00E9n es para ti" }), _jsxs("p", { className: "text-lg md:text-xl text-[#5C4A42] leading-relaxed", children: ["En ", _jsx("strong", { children: "NURAE" }), " creemos que cada mujer merece sentirse extraordinaria. Creamos piezas que celebran tu individualidad, combinando elegancia atemporal con precios que te permiten brillar sin l\u00EDmites."] }), _jsx("div", { className: "space-y-4", children: [
                                    "Materiales de alta calidad",
                                    "Diseños únicos y atemporales",
                                    "Precios accesibles para todas",
                                ].map((text, idx) => (_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "h-2 w-2 bg-[#D4AF37] rounded-full" }), _jsx("span", { className: "text-[#5C4A42]", children: text })] }, idx))) }), _jsxs("div", { className: "flex flex-col sm:flex-row gap-4", children: [_jsx(Link, { to: "/about", children: _jsx(Button, { className: "bg-[#2C1810] text-white hover:bg-[#3A221A] px-8 py-3 rounded-full font-medium shadow-lg hover:shadow-xl transition-all duration-300", children: "Conoce M\u00E1s" }) }), _jsx(Link, { to: "/collections", children: _jsx(Button, { variant: "outline", className: "border-[#2C1810] text-[#2C1810] hover:bg-[#2C1810] hover:text-white px-8 py-3 rounded-full font-medium transition-all duration-300", children: "Explorar Colecci\u00F3n" }) })] })] })] }) }) }));
}
