import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { LuUser, LuLogIn, LuUserPlus, LuHeart, LuPackage, LuSettings, LuLogOut, } from "react-icons/lu";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger, } from "@/components/ui/dropdown-menu";
import { Link } from "react-router-dom";
import { useAuthStore } from "@/stores/useAuthStore";
import { useLogout } from "@/hooks/auth/useLogout";
export function UserMenu() {
    const isAuthenticated = useAuthStore((state) => state.isAuthenticated);
    const user = useAuthStore((state) => state.user);
    const { mutate: logoutMutate, isPending } = useLogout();
    return (_jsxs(DropdownMenu, { children: [_jsx(DropdownMenuTrigger, { asChild: true, children: _jsxs(Button, { variant: "ghost", size: "icon", className: "hover:bg-pink-50 hover:text-primary transition-all duration-300 relative group", children: [_jsx(LuUser, { className: "h-5 w-5" }), _jsx("span", { className: "sr-only", children: "Cuenta de usuario" })] }) }), _jsx(DropdownMenuContent, { className: "w-56 bg-white/95 backdrop-blur-md border border-pink-100", align: "end", children: isAuthenticated ? (_jsxs(_Fragment, { children: [_jsx(DropdownMenuLabel, { className: "font-serif", children: "Mi Cuenta" }), _jsx(DropdownMenuSeparator, {}), _jsx(DropdownMenuItem, { asChild: true, children: _jsxs(Link, { to: `/${user.role}/profile`, className: "flex items-center gap-2", children: [_jsx(LuUser, { className: "h-4 w-4" }), "Perfil"] }) }), _jsx(DropdownMenuItem, { asChild: true, children: _jsxs(Link, { to: `/${user.role}/orders`, className: "flex items-center gap-2", children: [_jsx(LuPackage, { className: "h-4 w-4" }), "Mis Pedidos"] }) }), _jsx(DropdownMenuItem, { asChild: true, children: _jsxs(Link, { to: "/wishlist", className: "flex items-center gap-2", children: [_jsx(LuHeart, { className: "h-4 w-4" }), "Lista de Deseos"] }) }), _jsx(DropdownMenuItem, { asChild: true, children: _jsxs(Link, { to: `/${user.role}/settings`, className: "flex items-center gap-2", children: [_jsx(LuSettings, { className: "h-4 w-4" }), "Configuraci\u00F3n"] }) }), _jsx(DropdownMenuSeparator, {}), _jsxs(DropdownMenuItem, { className: "text-red-600 focus:text-red-600", onClick: () => logoutMutate(), disabled: isPending, children: [_jsx(LuLogOut, { className: "h-4 w-4 mr-2" }), "Cerrar Sesi\u00F3n"] })] })) : (_jsxs(_Fragment, { children: [_jsx(DropdownMenuLabel, { className: "font-serif", children: "Bienvenida" }), _jsx(DropdownMenuSeparator, {}), _jsx(DropdownMenuItem, { asChild: true, children: _jsxs(Link, { to: "/login", className: "flex items-center gap-2", children: [_jsx(LuLogIn, { className: "h-4 w-4" }), "Iniciar Sesi\u00F3n"] }) }), _jsx(DropdownMenuItem, { asChild: true, children: _jsxs(Link, { to: "/register", className: "flex items-center gap-2", children: [_jsx(LuUserPlus, { className: "h-4 w-4" }), "Crear Cuenta"] }) })] })) })] }));
}
